"""setup models

Revision ID: a82fc437863e
Revises: 
Create Date: 2026-02-22 11:02:30.409209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82fc437863e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance_logs', 'employees', ['pf'], ['pf'])
    op.create_foreign_key(None, 'employees', 'departments', ['department_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'attendance_logs', type_='foreignkey')
    # ### end Alembic commands ###
